CC = gcc

CFLAGS = -Wall -g -I./include

LIBS = -lsqlite3

SRC_DIR = src
OBJ_DIR = obj
BIN_DIR = bin
INCLUDE_DIR = include
DATA_DIR = data

SRC = $(wildcard $(SRC_DIR)/*.c)
OBJ = $(patsubst $(SRC_DIR)/%.c, $(OBJ_DIR)/%.o, $(SRC))

TARGET = $(BIN_DIR)/patient_db

all: dirs $(TARGET)

dirs:
	mkdir -p $(BIN_DIR) $(OBJ_DIR) $(DATA_DIR)

# Правило для создания исполняемого файла
$(TARGET): $(OBJ)
	$(CC) $(CFLAGS) -o $@ $^ $(LIBS)

$(OBJ_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ_DIR) $(BIN_DIR)/*.o $(TARGET)

run: all
	$(TARGET)

.PHONY: all clean run dirs