CC = gcc
CFLAGS = -Wall -Iinclude
SRCS = src/main.c src/patient.c src/file_io.c
OBJS = $(SRCS:.c=.o)
TARGET = patient_app

all: $(TARGET)

$(TARGET): $(SRCS)
	$(CC) $(CFLAGS) -o $@ $(SRCS)

clean:
	rm -f $(TARGET)
